jobs:
  include:
    - stage: "Instal addons on linux"
      name: "addons on focal distribution gpu xlarge"
      dist: focal
      addons:
        tensorflow: 1.6.0
        blender: 3.4.1
      vm:
        size: 'gpu-xlarge'
      language: python
      python:
        - "3.9"
      arch: 'amd64'
      script:
        - df -h
        - lspci
    - stage: "Instal addons on linux"
      name: "addons on focal distribution gpu medium"
      dist: focal
      addons:
        tensorflow: 1.6.0
        blender: 3.4.1
      vm:
        size: 'gpu-medium'
      language: python
      python:
        - "3.9"
      arch: 'amd64'
      script:
        - df -h
        - lspci
        - echo "Going for sleep"
      script:
        - |
          for ((i=1; i<=55; i++)); do
            echo "Elapsed minutes: $i"
            sleep 60s
          done
